//go:build (!no_base || ingres) && !no_ingres

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/ildus/usql/drivers/ingres" // Ingres (Actian X, Vector, VectorH) driver
)
